### ISSUE TITLE
response.raise_for_status()

### ISSUE THREAD

**Issue by AnthonyZJiang** [scottburlovich/pythonpancakes#3]
Hi, thanks for making the wrapper for the API.

I'd like to discuss this [code block](https://github.com/scottburlovich/pythonpancakes/blob/fea97d9a9912601b47d455155a5f3b4e41bb0f12/src/pythonpancakes/api.py#L37):

```python
        try:
            response.raise_for_status()
            return json.loads(response.content.decode('utf-8'))
        except Exception as err:
            try:
                content = json.loads(response.content.decode('utf-8'))
                raise ValueError(content)
            except json.decoder.JSONDecodeError:
                pass
            raise
```

When [`response.raise_for_status()`](https://github.com/psf/requests/blob/2ed84f55b22f19a1e1e8eea2e50963dce62052d3/requests/models.py#L930) raises `HTTPError`, the error gets caught by the `except` block, then you try to parse the content and raise a `ValueError`. Why is this better than simply let `raise_for_status()` raise the exception it wants to raise?

IMHO, `HTTPError` is the correct type of error to raise here. It makes more sense for your API users to catch `HTTPError` than `ValueError`. I assume you want to show the response from the server, but `response.content` has already been passed to `HTTPError` which can then be decoded by the API user as needed. 

In addition, I think
```
                content = json.loads(response.content.decode('utf-8'))
                raise ValueError(content)
```
can be simplified to
```
                raise ValueError(response.content.decode('utf-8'))
```
, because it converts dict back to str to print content anyways.

**Comment by AnthonyZJiang** [comment]
Also, I completely lack experience in this but do you need `__exit__` when you don't define `__enter__`?

**Comment by scottburlovich** [comment]
Hi, thank you for your PR which simplifies the exception handling in that code block.

As for `__enter__` and `__exit__`, these are context manager methods which are not really applicable given the way the wrapper is currently used. The only reason that the `__exit__` method is used is to ensure that any HTTP session opened to the PS API endpoint is closed immediately after the request. I thought about using the `__del__` destructor here which would fit better with `__init__`, but that would only be executed if the user deleted the class object that they previously initialized... for example:

```
ps = PancakeSwapAPI()
ps.summary()
del ps
```

**Comment by AnthonyZJiang** [comment]
Hi, thanks for your reply. It's my pleasure to help and I'm glad I helped.

I do not consider myself a good Python programmer nor being familiar with magic methods in Python, and it is very possible that I completely missed something that you have in knowledge. However, I would like to put forward my arguments below.

I cannot find anywhere that documents the use of `__exit__` without `__enter__`. I have searched google and [Python 3.9.6 documentation](https://docs.python.org/3.9/search.html?q=__exit__&check_keywords=yes&area=default). According to my readings, `__exit__` is only used and effective with context manager as it is only called when `__enter__` finishes. A simple test you can do is to add a line in `__exit__`:

```Python
def __exit__():
    print('__exit__ called.')
    self.session.close()
```
I cannot see `__exit__` getting called.

It may be reasonable to implement context manager here. [Aly Sivji's guide](https://alysivji.github.io/managing-resources-with-context-managers-pythonic.html#When-to-use-Context-Managers) suggests that it is a good idea to use context manager when you need to call `close()`. If you check [Requests.Session documentation](https://docs.python-requests.org/en/master/user/advanced/?highlight=session#session-objects), it also has its context manager.

**Comment by scottburlovich** [comment]
Thank you for pointing this mistake out - you are correct. I must have misinterpreted something when I quickly put this wrapper together. I'll just blame it on Python not being my primary language :)

Anyway, in order to not introduce breaking changes, I have simplified `__init__`, reworked `_get()` to use the requests wrapper as a context manager and have eliminated `__exit__`. If you want to pull down the 'develop' branch and re-submit another PR with your exception simplifications, I will make sure those are added in so you are attributed accordingly.

**Comment by AnthonyZJiang** [comment]
@scottburlovich 

I agree we should be more careful with adding the context manager. Also, there is room to improve the code (the updated `__get()`), but we should deal with it later after the exception handling improvement.

I updated the PR, didn't create a new one.

**Comment by scottburlovich** [comment]
Thank you for your help. PR merged and new release tagged!
