### ISSUE TITLE
Update time

### ISSUE THREAD

**Issue by Seifter75** [scottburlovich/pythonpancakes#7]
Hallo
Is possible down the update time?
Now is near at 5 minute,is possible set this time?
Thanks for your work.

**Comment by scottburlovich** [comment]
Hello,

I'm not sure I fully understand your question, but I believe you are asking about the response data being cached for 5 minutes?

If so, that is a limitation of the public API for PancakeSwap. This wrapper simply passes on the response it receives, and unfortunately has no control over this cache timeout.

**Comment by Seifter75** [comment]
Thanks 
You have understand my answer.
I search other library, i see for real-time price.
Regards
