### ISSUE TITLE
The v2 version of the api interface cannot be used

### ISSUE THREAD

**Issue by tokentailormm** [scottburlovich/pythonpancakes#8]
<img width="1145" alt="image" src="https://user-images.githubusercontent.com/81801957/200989984-c1bbca01-dc2e-425d-a043-c6118f93c4ae.png">

Requesting this interface to report an error, please help us to see how to solve this error.

request url：https://api.pancakeswap.info/api/v2/tokens/0xc864019047b864b6ab609a968ae2725dfaee808a
error：{'error': {'code': 500, 'message': 'GraphQL error: panic processing query: only derived fields can lead to multiple children here'}}

Please！

**Comment by scottburlovich** [comment]
Sorry, would love to help, but the problem lies with https://github.com/pancakeswap/pancake-info-api.
I cannot fix whatever issue is occurring, this package simply wraps the requests and responses for use in Python.
